
title: Bladmuziek omzetten in noten
hero_image: images/banner.png
description: Instructies voor het omzetten van bladmuziek in muzieknoten in MicroPython met behulp van picozero
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Bladmuziek omzetten in noten
