title: Turning sheet music into notes
hero_image: images/banner.png
description: Instructions on how to turn sheet music into notes in MicroPython using picozero
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - 
    title: Turning sheet music into notes
